# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Run Full Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Dependencies
        run: |
            sudo apt update
            sudo apt install -y xvfb ca-certificates net-tools netcat gnupg ffmpeg libgtk-3-0 libgdk-pixbuf2.0-dev libxcomposite-dev libdbus-glib-1-2 libatk-bridge2.0-0 wget libgbm1 libnss3 libxss1 libasound2 
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Setup MySQL Conncection
        run: |
          pip3 install mysql-connector-python

      - name: Setup Requirements
        run: |
          pip3 install -r requirements.txt    
      
      - name: Run Robot Init
        run: |
          rfbrowser init
      
      - name: Run Test Suites
        run: |
           robot -d ./log -L trace -v headless:chromium -v browser:true front/tests/
      
      - name: Upload Logs
        uses: actions/upload-artifact@v2.2.3
        with:
          path: ./log
